---

- name: Ensure MariaDB paths exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ mariadb_uid }}"
    group: "{{ mariadb_gid }}"
  with_items:
    - "{{ mariadb_base_path }}"
    - "{{ mariadb_bin_path }}"
    - "{{ mariadb_data_path }}"

- name: Ensure MariaDB configuration files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ mariadb_base_path }}/{{ item }}"
    owner: "{{ mariadb_uid }}"
    group: "{{ mariadb_gid }}"
    mode: 0640
  with_items:
    - env
    - my.cnf

- name: Ensure MariaDB scripts created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}.j2"
    dest: "{{ mariadb_bin_path }}/{{ item }}"
    mode: 0750
  with_items:
    - cli
    - cli-non-interactive
    - dump

- name: Ensure MariaDB container image is pulled
  community.docker.docker_image:
    name: "{{ mariadb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ mariadb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else mariadb_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure MariaDB container network is created
  community.general.docker_network:
    name: "{{ mariadb_container_network }}"
    driver: bridge

- name: Ensure MariaDB service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/mariadb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ mariadb_identifier }}.service"
    mode: 0640

- name: Ensure managed MariaDB databases prepared
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/util/prepare_managed_databases.yml"
    apply:
      tags:
        - always
  when: "mariadb_managed_databases | length > 0"

