# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: mariadb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: mariadb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-mariadb
    - install-all
    - install-mariadb

- block:
    - when: not mariadb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-mariadb

- block:
    - when: mariadb_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/upgrade.yml"
  tags:
    - upgrade-mariadb
