# SPDX-FileCopyrightText: 2023 - 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform MariaDB installation tasks
  when: mariadb_enabled | bool
  tags:
    - setup-all
    - setup-mariadb
    - install-all
    - install-mariadb
  block:
    - name: Validate MariaDB configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install MariaDB
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform MariaDB uninstallation tasks
  when: not mariadb_enabled | bool
  tags:
    - setup-all
    - setup-mariadb
  block:
    - name: Uninstall MariaDB
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"

- name: Perform MariaDB upgrade tasks
  when: mariadb_enabled | bool
  tags:
    - upgrade-mariadb
  block:
    - name: Upgrade MariaDB
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/upgrade.yml"
