---

- name: Fail if required MariaDB settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`) for using this role.
  when: "item.when | bool and vars[item.name] | length == 0"
  with_items:
    - {'name': 'mariadb_identifier', when: true}
    - {'name': 'mariadb_uid', when: true}
    - {'name': 'mariadb_gid', when: true}
    - {'name': 'mariadb_container_network', when: true}
    - {'name': 'mariadb_root_password', when: true}

- name: (Deprecation) Catch and report renamed MariaDB settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'mariadb_root_passsword', 'new': 'mariadb_root_password'}
