---

- name: Fail if required MariaDB settings not defined
  fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - mariadb_identifier
    - mariadb_uid
    - mariadb_gid
    - mariadb_container_network
    - mariadb_root_passsword
